name:                TimeLines
version:             0.1.0.0
github:              "lnfiniteMonkeys/TimeLines"
license:             GPL-3
author:              "lnfinite Monkeys"
maintainer:          "lnfiniteMonkeys@tuta.io"
copyright:           "2019 lnfinite Monkeys"

extra-source-files:
- README.md
- ChangeLog.md
- BootScript.hs

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

description:         Please see the README on GitHub at <https://github.com/lnfiniteMonkeys/TimeLines#readme>

dependencies:
- base >= 4.7 && < 5
- mtl == 2.2.2
- containers == 0.6.0.1
- deepseq == 1.4.4.0
- array == 0.5.3.0
- directory == 1.3.3.0
- filepath == 1.4.2.1
- hosc == 0.17
- hsndfile == 0.8.0
- async == 2.2.2

library:
  source-dirs: src

tests:
  timelines-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - timelines
