name:                TimeLines
version:             0.1.0.0
github:              "lnfiniteMonkeys/TimeLines"
license:             BSD3
author:              "lnfiniteMonkeys"
maintainer:          "example@example.com"
copyright:           "lnfiniteMonkeys"

extra-source-files:
- README.org
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/TimeLines#readme>

dependencies:
- base >= 4.7 && < 5
- hsndfile
- hosc
- directory

library:
  source-dirs: src

executables:
  TimeLines-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - TimeLines
    - hsndfile
    - hosc

tests:
  TimeLines-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - TimeLines
    - hsndfile
    - hosc